.\""
.Dd February 13, 2008
.Dt IIBDBV 1  
.Os Mac OS X       
.Sh NAME
.Nm iibdbv
.Nd Validate the ISO/IEC 19794-6 Iris Image Biometric Data Blocks that
are contained within a single file.
.Sh SYNOPSIS
.Nm
.Ar infile
.Pp
.Sh DESCRIPTION
The
.Nm
command is used to validate ISO/IEC 19794-6:2005 compliant iris image data
records that are contained within a single file. Exit codes are set based on
the result of the validation.
.Pp
.Sh RETURN VALUES
The
.Nm
command returns EXIT_SUCCESS (0) if the iris data records are valid,
EXIT_FAILURE if they are invalid, or some other error occurs
(failure to open the input file, for example).
.Sh EXAMPLES
.Nm
sample.iid
.Pp
Validate all the iris data records contained within the file.
.Pp
.Sh SEE ALSO
.Xr priibdb 1 ,
.Xr exit 3 .
.Sh STANDARDS
``Information technology - Biometric data interchange formats - Part 6: Iris
image data'', ISO/IEC 19794-6:2005, June 1, 2005.
.Sh NOTES
The
.Nm
program will be enhanced over time to support updates to the ISO standard,
in conjunction with the NIST Iris Image library.
.Sh HISTORY
Created February 13th, 2008 by NIST.
