.\""
.Dd June 20, 2005
.Dt PGM2FIR 1  
.Os Mac OS X       
.Sh NAME
.Nm pgm2fir
.Nd Convert a PGM file to an ANSI/INCITS-381 Finger Image Record.
.Sh SYNOPSIS
.Nm
.Ar pgmfile
.Ar outfile
.Op Fl p
.Pp
.Sh DESCRIPTION
The
.Nm
command is used to convert a PGM file (presumably containing a fingerprint
image) into an ANSI/INCITS-381 finger image record. The resulting record
is save to the output file. The image data is encoded to Wavelet Scalar 
Quantization (WSQ) prior to inclusion into the 381 record.
.Pp
This program uses the WSQ library that is distributed as part of the NIST
Fingerprint Image Software distribution, available at
http://www.itl.nist.gov/iad/894.03/databases/defs/nist_nfis.html.
.Ed
.Pp
The arguments are as follows:
.Bl -tag -width -indent
.It \&pgmfile
Specifies the input file containing PGM finger image.
.It \&firfile
Specifies the output file that will contain the 381 record.
.It Fl p
specifies the finger position number; the default is 2.
.El
.Sh EXAMPLES
\'pgm2fir inputimage.pgm outputimage.381'
.Pp
Produces a file containing the the finger image (WSQ encoded) and meta
data in 381-2004 format.
.Pp
\'pgm2fir -p 3 inputimage.pgm outputimage.381'
.Pp
Produces the 381 compliant file with the finger position set to 3.
.Pp
.Sh STANDARDS
``Finger Image-Based Data Interchange Format'', ANSI INCITS 381-2004,
American National Standard Institute, May, 2004.
.Sh HISTORY
Created June 20th, 2005 by NIST.
