.\""
.Dd March 10, 2005
.Dt MKFMR 1  
.Os Mac OS X       
.Sh NAME
.Nm mkfmr
.Nd Create M1 Finger Minutia Records
.Sh SYNOPSIS
.Nm
.Fl h
.Ar hdrinfo
.Fl f
.Ar fvmrinfo
.Fl x
.Ar xytinfo
.Fl o
.Ar outfile
.Op Fl r Ar ridgeinfo
.Op Fl c Ar coredeltainfo
.Op Fl p
.Pp
.Sh DESCRIPTION
The
.Nm
command is used to create a ANSI/ICITS 378-2004 compliant M1 minutiae record from a set of text files.  The M1 record is stored in a new file upon success.
.Pp
.Pp
.Bd -literal
mkfmr -h hdr.txt -f fvmr.txt -x xyt.txt -o m1.raw
.Ed
.Pp
The options are as follows:
.Bl -tag -width -indent
.It Fl h\ \&hdrinfo
Specifies the file containing M1 header info, single line, in this form:
.Bl -tag -width "Num-Views " -compact
.It Cm ID
The format ID ('FMR')
.It Cm Version
The Spec Version ('20')
.It Cm Length
Decimal record length; not currently used.
.It Cm CBEFF-ID
Hex CBEFF identifier
.It Cm Eqpt
Hex Capture Eqpt compliance and ID
.It Cm X-Size
Decimal X image size
.It Cm Y-Size
Decimal Y image size
.It Cm X-Res
Decimal X resolution
.It Cm Y-Res
Decimal Y resolution
.It Cm Num-Views
Decimal number of finger views
.El
.It Fl f\ \&fvmrinfo
Specifies the file containing the Finger View Minutiae Record (FVMR) info,
single line, in this form:
.Bl -tag -width "View/Type " -compact
.It Cm Position
Decimal finger postion number
.It Cm View/Type
Hex view number and impression type
.It Cm Quality
Decimal quality value
.It Cm Number
Decimal number of minutiae
.El
.It Fl x\ \&xytinfo
Specifies the file containing the minutiae info in coordinate/angle (X-Y-Theta)
format. Each minutiae is given on a single line, in this form:
.Bl -tag -width "Quality " -compact
.It Cm Index
Decimal index number; this is for convenience only as it is not part of the 
minutia record.
.It Cm Type 
Decimal minutiae type:
.Bl -tag -width "AA " -compact
.It Cm 0
Other
.It Cm 1
Ridge Ending
.It Cm 2
Bifurcation
.El
.It Cm X 
Decimal X coordinate
.It Cm Y 
Decimal Y coordinate
.It Cm Angle 
Decimal angle (theta)
.It Cm Quality
Decimal minutia quality
.El
.It Fl r\ \&ridgeinfo
Specifies the file containing ridge count data, multiple lines. The first line:
.Bl -tag -width "Extraction " -compact
.It Cm Extraction
Decimal extraction method
.It Cm Number
Decimal number of ridge counts
.El
.Pp
The remaining lines:
.Bl -tag -width "Index-One " -compact
.It Cm Index-One
The first ridge index number
.It Cm Index-Two
The second ridge index number
.It Cm Count
The number of ridges between Index-One and Index-Two
.El
.It Fl c\ \&coredeltainfo
Specifies the file containing the core/delta info. The first line is of this
form:
.Bl -tag -width "Number " -compact
.It Cm Type
Decimal core type
.It Cm Number
Decimal number of cores
.El
.Pp
Lines 2..n+1 (number of cores plus one) contain core info of this form:
.Bl -tag -width "Number " -compact
.It Cm X 
Decimal X coordinate
.It Cm Y 
Decimal Y coordinate
.It Cm Angle 
Decimal angle, if core type is not '00'; otherwise, not present
.El
.Pp
The next line (n+2) is of this form:
.Bl -tag -width "Number " -compact
.It Cm Type
Decimal delta type
.It Cm Number
Decimal number of deltas
.El
.Pp
The remaining lines contain info for one delta each, in this form:
.Bl -tag -width "Number " -compact
.It Cm X 
Decimal X coordinate
.It Cm Y 
Decimal Y coordinate
.It Cm Angle1
Decimal angle one, if delta type is not '00'; otherwise, not present
.It Cm Angle2
Decimal angle two, if delta type is not '00'; otherwise, not present
.It Cm Angle3
Decimal angle three, if delta type is not '00'; otherwise, not present
.El
.It Fl p
causes the created M1 record to be printed to the screen
.El
.Pp
Each of the data files, except the header, can contain information for
multiple finger views, allowing more than one view to be contained in the
single minutiae record that is created.
.Sh EXAMPLES
\'mkfmr -h hdr.txt -f fvmr.txt -x xyt.txt -o m1.raw'
.Pp
Produces an M1 record containing finger minutiae data (X-Y-Theta) only.
.Pp
\'mkfmr -h hdr.txt -f fvmr.txt -x xyt.txt -r rcs.txt -c cds.txt -o m1.raw'
.Pp
Produces an M1 record containing finger minutiae data (X-Y-Theta), 
ridge counts, and core/delta info.
.Pp
.Sh FILES
Example header info file:
.Bd -literal -compact
FMR 20  0 00000000 0000 191 357 197 197 01
.Ed
.Pp
Example FVMR info file:
.Bd -literal -compact
07 03 90 4
.Ed
.Pp
Example minutiae data file:
.Bd -literal -compact
1 1 25 383 135 80
2 2 38 297 118 60
3 1 46 222 112 90
4 1 53 346 129 30
.Ed
.Pp
Example ridge count data file:
.Bd -literal -compact
02 03
1 0 0
1 006 04
1 017 12
.Ed
.Pp
Example core/delta data file:
.Bd -literal -compact
01 02
200 250 90
100 150 45
01 04
343 232 100 110 120
203 104 156 166 176
436 214 33 43 53
130 319 57 67 77
.Ed
.Pp
The next example shows a complete set of data files for a single minutiae
record that contains two finger views:
.Pp
Header:
.Bd -literal -compact
FMR 20  0 00000000 0000 191 357 197 197 02
.Ed
.Pp
FVMR:
.Bd -literal -compact
02 03 90 2
07 03 90 2
.Ed
.Pp
Minutiae:
.Bd -literal -compact
1 1 25 383 135 90
2 2 38 297 118 80
3 2 46 222 112 60
4 0 53 346 129 100
.Ed
.Pp
Ridge count:
.Bd -literal -compact
02 02
1 0 0
1 006 04
02 01
1 017 12
.Ed
.Pp
The core/delta file contains no cores and no deltas for the second finger:
.Bd -literal -compact
01 03
200 250 90
100 150 45
50 50 123
01 04
343 232 100 110 120
203 104 156 166 176
436 214 33 43 53
130 319 57 67 77
00 00
00 00
.Ed
.Sh SEE ALSO
.Xr fmr2an2k 1 ,
.Xr prfmr 1 .
.Sh HISTORY
Created March 10th, 2005 by NIST.
.Pp
Multiple FVMR support added April 20th, 2006.
