.\""
.Dd March 18, 2005
.Dt FMR2AN2K 1  
.Os Mac OS X       
.Sh NAME
.Nm fmr2an2k
.Nd Convert ANSI-378 M1 Fingerprint Minutiae Records to ANSI/NIST 2000 Format.
.Sh SYNOPSIS
.Nm
.Fl i
.Ar m1file
.Fl o
.Ar an2kfile
.Op Fl f Ar imglist
.Op Fl t Ar type2info
.Op Fl v
.Pp
.Sh DESCRIPTION
The
.Nm
command is used to convert an ANSI/ICITS 378-2004 compliant M1 minutiae record 
to an ANSI/NIST 1-2000 record. M1 fingerprint minutiae is placed into Type-9
records. An optional list of image files can be provided, and those images
are placed into Type-13 records. An optional file can be specified that contains
information for the Type-2 record.
.Pp
.Pp
.Bd -literal
fmr2an2k -i m1.raw -o an2k.raw
.Ed
.Pp
The options are as follows:
.Bl -tag -width -indent
.It Fl i\ \&m1file
Specifies the input file containing M1 records, in raw form.
.It Fl o\ \&an2kfile
Specifies the output file that will contain the ANSI/NIST records.
.It Fl f\ \&imglist
Specifies the optional input file that contains a list of images to associate
with the fingerprint minutiae (Type-9 record). Each image is placed into a
Type-13 record with the Image Designation Character (IDC) matching the 
Type-9 record, in order.
.It Fl t\ \&type2info
Specifies the optional input file that contains information for the Type-2
ANSI/NIST records. Each line is of this form:
.Bl -tag -width "Whitespace " -compact
.It Cm Field  
The field number of the Type-2 record.
.It Cm Whitespace
A single whitespace character is used to separate the field number from the
next item. Use of a TAB character is recommended, although any whitespace
can be used. 
.It Cm Data
The data string to place in the Type-2 field. The string's maximum length is
MAX_TYPE2_FIELD_SIZE, as given in ``ELECTRONIC FINGERPRINT TRANSMISSION 
SPECIFICATION'' document. The data string can include any characters except
newline.
.El
.It Fl v
causes the M1 file to be verified before creating the output file.
.El
.Sh EXAMPLES
\'fmr2an2k -i m1.raw -o an2k.raw'
.Pp
Produces an ANSI/NIST record containing the minutiae, ridge count, and 
core/delta information placed into the proper records.
.Pp
\'fmr2an2k -i m1.raw -o an2k.raw -t type2.txt'
.Pp
Produces an ANSI/NIST record as above, along with the Type-2 record information
from the input file.
.Pp
.Sh SEE ALSO
.Xr mkfmr 1 ,
.Xr prfmr 1 ,
.Xr an2k2iaf 1 .
.Sh STANDARDS
``ELECTRONIC FINGERPRINT TRANSMISSION SPECIFICATION'', CJIS-RS-0010 (V7),
DoJ/FBI Criminal Justice Information Services, January, 1999.
.Sh HISTORY
Created March 18th, 2005 by NIST.
