.\""
.Dd August 15, 2006
.Dt MKFIR 1  
.Os Mac OS X       
.Sh NAME
.Nm mkfir
.Nd Create Finger Image Format Records
.Sh SYNOPSIS
.Nm
.Fl h
.Ar hdrinfo
.Fl f
.Ar fivrinfo
.Oo Fl to Ar type Oc
.Fl o
.Ar outfile
.Op Fl p
.Pp
.Sh DESCRIPTION
The
.Nm
command is used to create ANSI or ISO compliant Finger Image-Based
records from a set of ASCII text files and images. The resulting
records are written to the output file.
.Pp
The options are as follows:
.Bl -tag -width -indent
.It Fl h\ \&hdrinfo
Specifies the file containing general record header info, single line,
in this form:
.Bl -tag -width "Image Compression Algorithm" -compact
.It Cm Format ID
Char ("FIR")
.It Cm Version Number
Char ("010")
.It Cm Record Length
Decimal, not currently used
.It Cm CBEFF Product ID
Hex
.It Cm Capture Device ID
Hex
.It Cm Image Acquisition Level
Decimal
.It Cm Number of Fingers/Palms
Decimal
.It Cm Scale Units
Decimal
.It Cm Scan Resolution (horiz)
Decimal
.It Cm Scan Resolution (vert)
Decimal
.It Cm Image Resolution (horiz)
Decimal
.It Cm Image Resolution (vert)
Decimal
.It Cm Pixel Depth
Decimal
.It Cm Image Compression Algorithm
Decimal
.It Cm Reserved
Decimal
.El
.Pp
.It Fl f\ \&fivrinfo
Specifies the file containing information for the Finger Image View Record(s)
(FIVR). The FIVR
contains all the information for a single finger image, including the name
of the raster image file.
The FIVR input file contains pairs lines. The first line of each pair
contains the data for the finger image header record in this form:
.Bl -tag -width "Horizontal Line Length" -compact
.It Cm Length
Decimal, not currently used
.It Cm Finger/Palm Position
Decimal
.It Cm Count of Views
Decimal
.It Cm View Number
Decimal
.It Cm Image Quality
Decimal
.It Cm Impression Type
Decimal
.It Cm Horizontal Line Length
Decimal
.It Cm Vertical Line Length
Decimal
.It Cm Reserved
Decimal
.El
.Pp
The second line of the pair contains the name of the raster image file.
.Pp
.It Fl to\ \&type
Specifies the output file type.
.Pp
Valid types for the output file are:
.Bl -tag -width "ANSI" -compact
.It Cm ANSI
ANSI/INCITS 381-2004 format;
.It Cm ISO
ISO/IEC 19794-4:2005 format.
.El
The default output type is ANSI.
.It Fl o
specifies the name of the output file.
.Pp
.It Fl p
causes the created record(s) to be printed to the screen.
.El
.Pp
The record length field of the header and the length field of the FIVR
are read by
.Nm
but not used as these field values are calculated.
.Sh EXAMPLES
mkfir -h hdr.txt -f fivr.txt -o fir.raw
.Pp
Produces a file containing the finger image record(s) in ANSI format.
.Pp
mkfir -h hdr.txt -f fivr.txt -to ISO -o fir.raw
.Pp
Produces a file containing the finger image record(s) in ISO format.
.Sh FILES
Example header file:
.Bd -literal -compact
FIR 010 0 0x0001000f 0x0000 31 2 1 500 500 500 500 8 3 0
.Ed
.Pp
Example FIVR file:
.Bd -literal -compact
0 7 1 1 3 0 368 380 0
lfing.jpg
0 2 1 1 3 0 368 380 0
rfing.jpg
.Ed
.Sh SEE ALSO
.Xr prfir 1 .
.Sh STANDARDS
``Finger Image-Based Data Interchange Format'', ANSI/INCITS 381-2004,
May 13, 2004.
.Pp
``Information technology - Biometrita interchange formats - Part 4:
Finger image data'', ISO/IEC 19794-4:2004, 2005-06-01.
.Sh HISTORY
Created August 15th, 2006 by NIST.
.Pp
Added support for ISO format, August 28 2008 by NIST.
