.\""
.Dd November 26, 2007
.Dt FMRMOD 1  
.Os Mac OS X       
.Sh NAME
.Nm fmrmod
.Nd Modify INCITS-378 finger minutiae
.Sh SYNOPSIS
.Nm
.Fl i
.Ar infile
.Fl o
.Ar outfile
.Fl q
.Ar value
.Pp
.Sh DESCRIPTION
The
.Nm
command is used to modify minutiae contained in an INCITS-378 input file.
Each minutia record within the input file is modified according to the
options specified. Currently, on the quality value can be changed, using the
.Fl q
option. The only constraint on the value is that it must be greater than
zero. In the minutia records, the value will be converted to the correct
size, so truncation may occur. All other fields of the finger minutiae
record, including extended data, are left unmodified.
.Pp
The options are as follows:
.Bl -tag -width "-o outfile"
.It Fl i\ \&infile
Specifies the file containing a complete M1 Finger Minutiae Format as specified
by ANSI/INCITS 378-2004.
.It Fl o\ \&outfile
Specifies the file that will contain the modified set of minutiae. This file
must not exist.
.It Fl q\ \&value
Specifies the minutia quality value.
.El
.Sh EXAMPLES
fmrmod -i m1.raw -o newm1.raw -q 16
.Pp
Produces a new file containing the minutia records from the input file with
quality values set to 16, and any extended data.
.Pp
.Sh SEE ALSO
.Xr mkfmr 1 ,
.Xr prfmr 1 ,
.Xr fmrplot 1 .
.Sh HISTORY
Created November 26th, 2007 by NIST.
