name: Check Code Formatting

permissions:
  contents: read

on:
  pull_request:
    paths:
      - '**.c'
      - '**.h'
      - '**.cpp'
      - '**.hpp'
      - '.clang-format'
      - '.github/workflows/clang-format.yml'
  push:
    branches:
      - master
    paths:
      - '**.c'
      - '**.h'
      - '**.cpp'
      - '**.hpp'
      - '.clang-format'
      - '.github/workflows/clang-format.yml'

jobs:
  clang-format:
    name: clang-format
    runs-on: ubuntu-26.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@v7
      with:
        submodules: false

    - name: Run clang-format
      shell: bash
      run: |
        # Make sure clang-format exists
        cf_vers=22
        command -v clang-format-${cf_vers} >/dev/null || { echo "::error ::clang-format-${cf_vers} not found"; exit 1; }

        # Make sure expected code exists
        [ -d NFIQ2 ] || { echo "::error ::NFIQ2 not found"; exit 1; }

        echo -n "Checking coding style with clang-format ${cf_vers}..."
        fail=0

        while IFS= read -r -d '' i; do
            # Protect against possible injection
            if [[ ! "$i" =~ ^[A-Za-z0-9._/+-]+$ ]]; then
                echo
                echo "::error ::Refusing to process file with unexpected name"
                exit 1
            fi

            if ! clang-format-${cf_vers} --Werror --dry-run "${i}" > /dev/null 2>&1;
            then
                if [ "${fail}" == "0" ]; then
                    echo "[FAIL]"
                    echo "::group::Required Fix-up Commands"
                fi
                fail=1
                msg="::warning file=${i}::Please run clang-format-${cf_vers} "
                msg+="-i ${i}"
                echo "${msg}"
            fi
        done < <(find NFIQ2 \( -name "*.c" -o -name "*.h" \
            -o -name "*.cpp" -o -name "*.hpp" \) \
            -a \! -name 'RandomForestTrainedParams.h' -print0)
        if [ "${fail}" == "1" ]; then
            echo "::endgroup::"
            msg="Please run the above files through clang-format ${cf_vers} "
            msg+="using the .clang-format configuration and push your changes "
            msg+="to the same branch. See CONTRIBUTING.md for more information."
            echo "::error ::${msg}"
            exit 1
        else
            echo "[OKAY]"
        fi
