set( NFIQ2_PRODUCT_NAME "ISO-IEC 29794-4 NFIQ2")
set( NFIQ2_PRODUCT_COPYRIGHT "Copyright \\xA9 2017 to the present" )
set( NFIQ2_PRODUCT_VENDOR "ISO-IEC SC37")
set( NFIQ2_VERSION_MAJOR "2")
set( NFIQ2_VERSION_MINOR "0")
set( NFIQ2_VERSION_EVOLUTION "1")

if(NOT DEFINED NFIQ2_VERSION_BUILD OR "${NFIQ2_VERSION_BUILD}" STREQUAL "")
  execute_process( COMMAND git rev-list --all	COMMAND wc -l OUTPUT_VARIABLE gitOut ERROR_VARIABLE gitErr)
  if("${gitErr}" STREQUAL "")
    STRING(REGEX REPLACE "(\r?\n)+$" "" "gitOut" "${gitOut}")
    if("${gitOut}" STREQUAL "")
      set(NFIQ2_VERSION_BUILD "0")
      message("Warning: use default build number of ${NFIQ2_VERSION_BUILD}")
    else()
      set(NFIQ2_VERSION_BUILD "${gitOut}")
    endif()
  else()
    set(NFIQ2_VERSION_BUILD "0")
  endif()
endif()

set( VERSION_SUFFIX "${CMAKE_CXX_COMPILER_ID}.${TARGET_PLATFORM}")

if("${TARGET_PLATFORM}" MATCHES "linux*")
  set( VERSION_VISIBILITY_ATTRIBUTE "__attribute__( ( section( \".nfiq2_version_info\" ) ) ) __attribute__( ( visibility( \"default\" ) ) )")
else()
  set( VERSION_VISIBILITY_ATTRIBUTE "")
endif()

if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/version.cpp.in")
  configure_file(version.cpp.in ${CMAKE_CURRENT_SOURCE_DIR}/version.${VERSION_SUFFIX}.cpp)
  set(VERSION_FILES ${CMAKE_CURRENT_SOURCE_DIR}/version.${VERSION_SUFFIX}.cpp)
endif()

if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/version.rc.in")
    configure_file(version.rc.in ${CMAKE_CURRENT_SOURCE_DIR}/version.${VERSION_SUFFIX}.rc)
    set(VERSION_FILES ${VERSION_FILES} ${CMAKE_CURRENT_SOURCE_DIR}/version.${VERSION_SUFFIX}.rc)
endif()
